shell = "zsh"

link_rules = true

platforms = [
  "linux",
  "arch",
  "x11",
  "xfce",
  "lightdm",
]

editors = [
  "zed",
]

tools = [
  "ghostty",
  "tmux",
  "yazi",
]

extras = [
  "arch-x11/lightdm-locale.xprofile",
  "arch-x11/mouse-workspace-buttons.xbindkeysrc",
  "arch-x11/touchpad-workspace-gestures.conf",
  "arch-x11/xfce-theme-toggle",
  "arch-x11/conky/conky.conf",
  "arch-x11/conky/conky.desktop",
  "arch-x11/conky/conky-battery",
  "arch-x11/conky/conky-gpu",
  "arch-x11/conky/conky-cpu-temp",
  "arch-x11/conky/conky-gpu-temp",
  "arch-x11/window-management/center-window",
  "arch-x11/window-management/tile-window",
  "arch-x11/zathura/zathurarc",
  "pc/path-aliases.sh",
  "pc/ssh-agent.sh",
]
